---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httplocalratelimitpolicies.policy.linkerd.io
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
spec:
  group: policy.linkerd.io
  names:
    kind: HTTPLocalRateLimitPolicy
    plural: httplocalratelimitpolicies
    singular: httplocalratelimitpolicy
    shortNames: [hlrlpolicy]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              required: [targetRef]
              properties:
                targetRef:
                  description: >-
                    TargetRef references a resource to which the rate limit
                    policy applies.
                  type: object
                  required: [kind, name]
                  properties:
                    group:
                      description: >-
                        Group is the group of the referent. When empty, the
                        Kubernetes core API group is inferred.
                      maxLength: 253
                      pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                      type: string
                    kind:
                      description: Kind is the kind of the referent.
                      maxLength: 63
                      minLength: 1
                      pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                      type: string
                    name:
                      description: Name is the name of the referent.
                      maxLength: 253
                      minLength: 1
                      type: string
                total:
                  description: >-
                    Overall rate-limit, which all traffic coming to this
                    target should abide.
                    If unset no overall limit is applied.
                  type: object
                  required: [requestsPerSecond]
                  properties:
                    requestsPerSecond:
                      format: int64
                      type: integer
                identity:
                  description: >-
                    Fairness for individual identities; each separate client,
                    grouped by identity, will have this rate-limit.
                  type: object
                  required: [requestsPerSecond]
                  properties:
                    requestsPerSecond:
                      format: int64
                      type: integer
                overrides:
                  description: Overrides for traffic from a specific client.
                  type: array
                  items:
                    type: object
                    required: [requestsPerSecond, clientRefs]
                    properties:
                      requestsPerSecond:
                        format: int64
                        type: integer
                      clientRefs:
                        type: array
                        items:
                          type: object
                          required: [kind, name]
                          properties:
                            group:
                              description: >-
                                Group is the group of the referent. When empty, the
                                Kubernetes core API group is inferred.
                              maxLength: 253
                              pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                              type: string
                            kind:
                              description: Kind is the kind of the referent.
                              maxLength: 63
                              minLength: 1
                              pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                              type: string
                            namespace:
                              description: >-
                                  Namespace is the namespace of the referent.
                                  When unspecified (or empty string), this refers to the
                                  local namespace of the Policy.
                              maxLength: 63
                              minLength: 1
                              pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                              type: string
                            name:
                              description: Name is the name of the referent.
                              maxLength: 253
                              minLength: 1
                              type: string
